spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    password: mylava
    database: 0
    #redis连接池配置
    jedis:
      pool:
        max-idle: 500
        max-wait: 500
        max-active: 1000

foolox:
  ioServer:
    port: 9000
    #会话超时时间10分钟
    timeout: 600000
    machineType: bullfight
  test:
    checkAuth: false





