server:
  port: 8000
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/foolox_game
  #rediskey
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    password: mylava
    database: 0
    #redis连接池配置
    jedis:
      pool:
        max-idle: 500
        max-wait: 500
        max-active: 1000



